//! `stozher-core` — the reference implementation of the Stozher `stozher/0.1` primitives.
//!
//! The normative specification is in `spec/` at the repository root; this crate implements it and
//! is validated against `spec/vectors/` by `cargo test`. Where the two disagree, **the
//! specification is authoritative and this crate is buggy** — except for the vectors themselves,
//! which are generated by an independent implementation and are authoritative over both.
//!
//! # What is here
//!
//! | Module | Specification section |
//! |---|---|
//! | [`jcs`] | 01 §3 — JCS (RFC 8785) canonicalization |
//! | [`decimal`] | 01 §2.5, 03 §4.3 — exact comparison of monetary decimal strings |
//! | [`crypto`] | 01 §1, §6 — SHA-256, Ed25519, SLIP-0010 |
//! | [`signed`] | 01 §4–§5 — key identifiers, the signed-object pattern |
//! | [`envelope`] | 02 — envelope structure |
//! | [`mandate`] | 03 — mandate chain verification |
//! | [`chain`] | 04 — hash chain and checkpoints |
//! | [`gate`] | 06 — gate authorization |
//! | [`payload`] | 04 §5 — evidence payload binding and decay |
//!
//! There are no HTTP, storage or transport concerns in this crate; those belong to
//! `stozher-kernel` (S1).
//!
//! # Two invariants this crate exists to enforce
//!
//! **Authorization is a signature, never a flag.** [`gate::verify_authorization`] is the only way an
//! action of a gated class becomes permitted, and it binds the approval to the exact subject,
//! mandate, policy version, classification, action, target and argument hash. No function in this
//! crate accepts an "approved" boolean, and [`envelope::validate`] rejects any envelope member that
//! is not in the closed schema — so there is nowhere for one to be smuggled.
//!
//! **Chain integrity does not depend on payload presence.** [`chain::verify_chain`] never reads a
//! payload, because envelopes commit to `evidence.payload-hash` and never contain the payload
//! itself. Erasing evidence for GDPR purposes cannot alter, and cannot be detected by, the chain.
//!
//! # Example
//!
//! ```
//! use stozher_core::{jcs, signed};
//!
//! // Canonicalization is by UTF-16 code unit, and numbers follow ECMAScript Number::toString.
//! let value = jcs::parse(r#"{"b":1e30,"a":-0}"#).unwrap();
//! assert_eq!(jcs::canonicalize(&value).unwrap(), r#"{"a":0,"b":1e+30}"#);
//!
//! // Signing covers the object without `sig`; the object id covers it with.
//! let signed = signed::sign_object(&value, &[7u8; 32]).unwrap();
//! assert!(signed::verify_signed_object(&signed).is_ok());
//! ```

pub mod chain;
pub mod crypto;
pub mod decimal;
pub mod envelope;
pub mod error;
pub mod gate;
pub mod jcs;
pub mod mandate;
pub mod payload;
pub mod signed;
pub mod trigger;

pub use error::{Error, Result};

/// The wire version string this crate implements.
pub const VERSION: &str = "stozher/0.1";
