//! `stozher-kernel revoke` — the object an operator signs, checked against the corpus that both
//! implementations agree on.
//!
//! Asserted against the real binary because the risk is not in the library: the members and the
//! canonical encoding are what a *second* implementation will read, and the corpus in
//! `spec/vectors/` is the only place where what they read is written down once. A CLI that grew a
//! member, dropped one, or emitted `reason: null` where the object should carry no `reason` would
//! still verify as a signed object and would still satisfy every test written against this side.
//!
//! `revoke` prints the object on stdout and everything else on stderr, so `bin/stozher-revoke` can
//! pipe it into a second process without a parser. That split is asserted here too — a stray log
//! line on stdout makes the pipe carry something the kernel refuses, and the operator sees a
//! signature failure instead of a stray line.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{fs, process};

use serde_json::Value;

/// The member set every revocation object in the corpus carries.
///
/// Read, not written down here. The corpus is generated by an independent implementation and
/// consumed by both, so it is the one description of this object that cannot quietly agree with
/// the code under test.
fn corpus_members() -> BTreeSet<String> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../spec/vectors/mandate-chain.json");
    let document: Value =
        serde_json::from_str(&fs::read_to_string(path).expect("the corpus")).expect("valid JSON");
    let mut members: Option<BTreeSet<String>> = None;
    for vector in document["vectors"].as_array().expect("vectors") {
        for revocation in vector["revocations"].as_array().unwrap_or(&Vec::new()) {
            let seen: BTreeSet<String> = revocation
                .as_object()
                .expect("a revocation object")
                .keys()
                .cloned()
                .collect();
            match &members {
                None => members = Some(seen),
                Some(first) => assert_eq!(
                    first, &seen,
                    "the corpus itself disagrees about a revocation object's members"
                ),
            }
        }
    }
    let members = members.expect("the corpus carries at least one revocation object");
    assert!(
        members.contains("reason"),
        "this test's negative case assumes the corpus objects carry a reason"
    );
    members
}

fn seed_in(name: &str) -> (PathBuf, PathBuf) {
    let dir = std::env::temp_dir().join(format!("stozher-revoke-{name}-{}", process::id()));
    fs::create_dir_all(&dir).expect("scratch directory");
    let seed = dir.join("operator.seed");
    let _ = fs::remove_file(&seed);
    let status = Command::new(env!("CARGO_BIN_EXE_stozher-kernel"))
        .args(["keygen", "--out"])
        .arg(&seed)
        .status()
        .expect("running keygen");
    assert!(status.success(), "keygen failed");
    (seed, dir)
}

fn revoke(seed: &Path, extra: &[&str]) -> (Value, String) {
    let output = Command::new(env!("CARGO_BIN_EXE_stozher-kernel"))
        .args(["revoke", "--mandate", &"a".repeat(64), "--key"])
        .arg(seed)
        .args(["--role", "0", "--index", "0"])
        .args(extra)
        .output()
        .expect("running the kernel binary");
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
    assert!(output.status.success(), "revoke failed:\n{stdout}{stderr}");
    let object = serde_json::from_str(stdout.trim())
        .unwrap_or_else(|e| panic!("stdout is not one JSON object ({e}):\n{stdout}"));
    (object, stderr)
}

#[test]
fn the_signed_object_carries_exactly_the_members_the_corpus_describes() {
    let (seed, dir) = seed_in("members");
    let (object, stderr) = revoke(&seed, &["--reason", "laptop lost"]);

    let members: BTreeSet<String> = object
        .as_object()
        .expect("an object")
        .keys()
        .cloned()
        .collect();
    assert_eq!(
        members,
        corpus_members(),
        "the CLI and the cross-language corpus describe different objects"
    );
    // The signature verifies as an ordinary signed object — the same check ingest runs, so a
    // revocation this command produces is one the kernel can evaluate for authority.
    let signer = stozher_core::signed::verify_signed_object(&object).expect("the signature");
    assert_eq!(
        signer.as_str(),
        object["sig"]["key"].as_str().expect("a signing key")
    );
    // Everything a human reads is on stderr, so stdout is a pipe and not a transcript.
    assert!(stderr.contains("signed by"), "{stderr}");

    let _ = fs::remove_dir_all(dir);
}

#[test]
fn an_unstated_reason_is_an_absent_member_and_not_a_null() {
    // §03 §7: `reason` is present in the envelope iff it is present in the object. A `null` here
    // would be a member the envelope's projection cannot match, so every revocation signed without
    // a reason would be refused as `revocation-object-mismatch` — at submission, by which point the
    // operator has already been told the signature was produced.
    let (seed, dir) = seed_in("no-reason");
    let (object, _) = revoke(&seed, &[]);

    assert!(
        object.get("reason").is_none(),
        "an unstated reason must not appear at all: {object}"
    );
    let mut expected = corpus_members();
    expected.remove("reason");
    let members: BTreeSet<String> = object
        .as_object()
        .expect("an object")
        .keys()
        .cloned()
        .collect();
    assert_eq!(members, expected);

    let _ = fs::remove_dir_all(dir);
}
